#!/usr/bin/env python
#
# This program scans SCAP xccdf content and compares 
# it to the ansible content to determine differences
# This presumes that the ansible tasks are following
# the proper naming convention as implemented in the
# ansible lockdown project.
#
# Author: Jonathan Davila <jdavila@redhat.com>

import untangle

raw_data = untangle.parse('xccdf.xml')

for i in raw_data.Benchmark.Group:
    print i['id']
